# Face Detection using HAAR Cascade Classifiers

In [1]:
import numpy as np
import cv2

In [3]:
# We point OpenCV's CascadeClassifier function to where our classifier (XML file format) is stored
face_classifier = cv2.CascadeClassifier(r"C:\Users\POOJA\Downloads\haarcascade_frontalface_default.xml")

In [4]:
# Load our image then convert it to grayscale
image = cv2.imread(r"C:\Users\POOJA\OneDrive\Pictures\images\happpy\6.jpeg")

In [5]:
image

array([[[ 50,  56,  67],
        [ 46,  52,  63],
        [ 41,  49,  62],
        ...,
        [144, 177, 173],
        [156, 183, 180],
        [159, 183, 181]],

       [[ 45,  51,  62],
        [ 42,  48,  59],
        [ 38,  46,  59],
        ...,
        [152, 183, 180],
        [160, 187, 184],
        [160, 184, 182]],

       [[ 44,  50,  61],
        [ 42,  48,  59],
        [ 39,  47,  60],
        ...,
        [160, 191, 190],
        [163, 189, 189],
        [155, 179, 179]],

       ...,

       [[211, 198, 182],
        [212, 199, 183],
        [213, 200, 184],
        ...,
        [154, 159, 168],
        [154, 159, 168],
        [152, 157, 166]],

       [[210, 197, 181],
        [212, 199, 183],
        [212, 199, 183],
        ...,
        [153, 158, 167],
        [153, 158, 167],
        [150, 155, 164]],

       [[210, 197, 183],
        [211, 198, 184],
        [211, 198, 184],
        ...,
        [158, 160, 170],
        [158, 161, 169],
        [155, 158, 166]]

In [6]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [7]:
gray

array([[ 59,  55,  52, ..., 172, 179, 180],
       [ 54,  51,  49, ..., 179, 183, 181],
       [ 53,  51,  50, ..., 187, 186, 176],
       ...,
       [195, 196, 197, ..., 161, 161, 159],
       [194, 196, 196, ..., 160, 160, 157],
       [194, 195, 195, ..., 163, 163, 160]], dtype=uint8)

In [8]:
# Our classifier returns the ROI of the detected face as a tuple
# It stores the top left coordinate and the bottom right coordiantes
faces = face_classifier.detectMultiScale(gray,1.3,5)            #rectangle 

In [9]:
faces

array([[447, 180, 242, 242],
       [692, 571, 224, 224]])

In [ ]:
# When no faces detected, face_classifier returns and empty tuple
if faces is():
    print("No faces found")

# We iterate through our faces array and draw a rectangle over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(127,0,255),2)
    cv2.imshow('face Detection',image)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\POOJA\AppData\Local\Temp\ipykernel_12052\3307698094.py:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is():
